force-app/main/default/objects/Sales_Funnel__c/Sales_Funnel__c.object-meta.xml
<CustomObject>
    <label>Monthly Sales Pipeline</label>
    <nameField>
        <displayFormat>SF -{0000}</displayFormat>
        <label>Monthly Sales Pipeline Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Sales Pipeline</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Funnel__c/fields/Business_Clients__c.field-meta.xml
<CustomField>
    <fullName>Business_Clients__c</fullName>
    <label>Business Clients</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Designer</fullName>
            </value>
            <value>
                <fullName>Retails Customer</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Door_Application__c.field-meta.xml
<CustomField>
    <fullName>Door_Application__c</fullName>
    <label>Door Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Door_Application</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Door_Category__c.field-meta.xml
<CustomField>
    <fullName>Door_Category__c</fullName>
    <label>Door Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Door_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
            <value>
                <fullName>Wes Team</fullName>
            </value>
            <value>
                <fullName>Own</fullName>
            </value>
            <value>
                <fullName>Repeat</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Order_Staus__c.field-meta.xml
<CustomField>
    <fullName>Order_Staus__c</fullName>
    <label>Order Staus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yet to submit the quote</fullName>
            </value>
            <value>
                <fullName>quote submitted</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Lead won</fullName>
            </value>
            <value>
                <fullName>Lead lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Order_Time_line_Time_Frame_Month__c.field-meta.xml
<CustomField>
    <fullName>Order_Time_line_Time_Frame_Month__c</fullName>
    <label>Order Time line/ Time Frame Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Order_Time_line_Time_Frame_Year__c.field-meta.xml
<CustomField>
    <fullName>Order_Time_line_Time_Frame_Year__c</fullName>
    <label>Order Time line/ Time Frame	Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Project_Category__c.field-meta.xml
<CustomField>
    <fullName>Project_Category__c</fullName>
    <label>Project Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Reason_for_Loosing_the_Order__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Loosing_the_Order__c</fullName>
    <label>Reason for Loosing the Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Budget Issue</fullName>
            </value>
            <value>
                <fullName>CPL Veneer</fullName>
            </value>
            <value>
                <fullName>Custom / Features</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Postpone</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PicklistHelperController.cls
public class PicklistHelperController {
    @AuraEnabled(cacheable=true)
    public static Map<String, List<String>> getMultiplePicklistOptions() {
        Map<String, List<String>> picklistMap = new Map<String, List<String>>();
        
        //Define Fields
        Schema.DescribeFieldResult businessClientsField = Sales_Funnel__c.Business_Clients__c.getDescribe();
        Schema.DescribeFieldResult projectCategoryField = Sales_Funnel__c.Project_Category__c.getDescribe();
        Schema.DescribeFieldResult projectSiteStageField = Sales_Funnel__c.Project_Site_Stage__c.getDescribe();
        Schema.DescribeFieldResult stateField = Sales_Funnel__c.State__c.getDescribe();
        Schema.DescribeFieldResult statusField = Sales_Funnel__c.Status__c.getDescribe();
        Schema.DescribeFieldResult regionField = Sales_Funnel__c.Region__c.getDescribe();
        Schema.DescribeFieldResult orderStatusField = Sales_Funnel__c.Order_Staus__c.getDescribe();
        Schema.DescribeFieldResult yearField = Sales_Funnel__c.Order_Time_line_Time_Frame_Year__c.getDescribe();
        Schema.DescribeFieldResult monthField = Sales_Funnel__c.Order_Time_line_Time_Frame_Month__c.getDescribe();
        Schema.DescribeFieldResult reasonLostField = Sales_Funnel__c.Reason_for_Loosing_the_Order__c.getDescribe();
        Schema.DescribeFieldResult doorAppField = Sales_Funnel__c.Door_Application__c.getDescribe();
        Schema.DescribeFieldResult doorCatField = Sales_Funnel__c.Door_Category__c.getDescribe();
        Schema.DescribeFieldResult leadSourceField = Sales_Funnel__c.Lead_Source__c.getDescribe();
        
        //Helper method to get values
        picklistMap.put('Business_Clients__c', getValues(businessClientsField));
        picklistMap.put('Status__c', getValues(statusField));
        picklistMap.put('Project_Site_Stage__c', getValues(projectSiteStageField));
        picklistMap.put('Project_Category__c', getValues(projectCategoryField));
        picklistMap.put('Reason_for_Loosing_the_Order__c', getValues(reasonLostField));
        picklistMap.put('Door_Category__c', getValues(doorCatField));
        picklistMap.put('Door_Application__c', getValues(doorAppField));
        picklistMap.put('Region__c', getValues(regionField));
        picklistMap.put('State__c', getValues(stateField));
        picklistMap.put('Order_Time_line_Time_Frame_Month__c', getValues(monthField));
        picklistMap.put('Order_Time_line_Time_Frame_Year__c', getValues(yearField));
        picklistMap.put('Order_Staus__c', getValues(orderStatusField));
        picklistMap.put('Lead_Source__c', getValues(leadSourceField));
        
        return picklistMap;
    }
    
    private static List<String> getValues(Schema.DescribeFieldResult fieldResult) {
        List<String> values = new List<String>();
        for (Schema.PicklistEntry entry : fieldResult.getPicklistValues()) {
            if (entry.isActive()) {
                values.add(entry.getLabel());
            }
        }
        return values;
    }

}