force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit-{000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CheckInCheckOutController.cls
public class CheckInCheckOutController {
    @AuraEnabled
    public static void updateVisitCheckIn (decimal latitude, decimal longitude,string visitId) {
        // Query the Visit record by Id
        Visit__c visit = [SELECT Id,Actual_Start_Time__c, Actual_End_Time__c, Check_In_Location__Longitude__s, Check_In_Location__Latitude__s,Check_Out_Location__Latitude__s, Check_Out_Location__Longitude__s, Status__c FROM Visit__c WHERE Id = :visitId LIMIT 1];
       
            visit.Actual_Start_Time__c = System.now();
            visit.Check_In_Location__Longitude__s = latitude;
            visit.Check_In_Location__Latitude__s = longitude;
            visit.Status__c = 'In Progress' ;
         update visit;
 
    }
}