force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit-{000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Key_Account__c.field-meta.xml
<CustomField>
    <fullName>Key_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Key Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Planned_Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Visit_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Planned Visit Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Related_to__c.field-meta.xml
<CustomField>
    <fullName>Related_to__c</fullName>
    <label>Related to</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VisitTriggerHandlerTest.cls
@isTest
public class VisitTriggerHandlerTest {
    @isTest
    public static void VisitTest() {
        Profile p = [SELECT Id FROM Profile  LIMIT 1];
         
        User u = new User(Alias = 'standt12', Email='standarduser@testorgfil.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com.123',MobilePhone = '111');
        insert  u;
        
        Account a = new Account(Name = 'TestAccount', OwnerId = u.Id);
        insert a;
        
        Visit__c v = new Visit__c(Planned_Visit_Date__c = system.today(), Visit_Type__c = 'New Visit', Related_to__c = 'Key Account', Key_Account__c = a.Id);
        insert v;
        
        String visitId = v.Id;
        CheckInCheckOutController.updateVisitCheckIn(12.971599, 77.594566, visitId);

    }
    
    /*@isTest
    public static void CheckINCheckOutTest() {
        String visitId;
        List<Visit__c> lstV = [SELECT Id FROM Visit__c LIMIT 1];
        for(Visit__c v : lstV) {
            visitId = v.Id;
        }
        
        
    }*/
}