force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Alternate_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Mobile__c</fullName>
    <label>Alternate Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Appx_Display_Space_They_Own_Sqft__c.field-meta.xml
<CustomField>
    <fullName>Appx_Display_Space_They_Own_Sqft__c</fullName>
    <label>Appx Display Space They Own (----Sqft)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Architect_Name__c.field-meta.xml
<CustomField>
    <fullName>Architect_Name__c</fullName>
    <label>Architect Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Company_Location__c.field-meta.xml
<CustomField>
    <fullName>Company_Location__c</fullName>
    <label>Company Location</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Display_Size_can_be_given_to_Westeam__c.field-meta.xml
<CustomField>
    <fullName>Display_Size_can_be_given_to_Westeam__c</fullName>
    <label>Display Size can be given to Westeam</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Display__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Display_Size_can_be_given_to_Westeam</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Existing_Business_experience_in_this_Ind__c.field-meta.xml
<CustomField>
    <fullName>Existing_Business_experience_in_this_Ind__c</fullName>
    <inlineHelpText>Existing Business experience in this Industry or Different</inlineHelpText>
    <label>Existing Business experience in this Ind</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Exiting_Business__c.field-meta.xml
<CustomField>
    <fullName>Exiting_Business__c</fullName>
    <label>Exiting Business</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Looking_for_Wesmarc_dealership__c.field-meta.xml
<CustomField>
    <fullName>Looking_for_Wesmarc_dealership__c</fullName>
    <inlineHelpText>Looking for Wesmarc dealership, requesting to brief the T&amp;C to proceed further</inlineHelpText>
    <label>Looking for Wesmarc dealership</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Showroom_Address__c.field-meta.xml
<CustomField>
    <fullName>Showroom_Address__c</fullName>
    <label>Showroom Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <label>Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarded</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Sub_Source__c</fullName>
    <label>Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Source_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Tentative_Date_of_Lead_Closure__c.field-meta.xml
<CustomField>
    <fullName>Tentative_Date_of_Lead_Closure__c</fullName>
    <label>Tentative Date of Lead Closure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tentative_Date_of_Lead_Closure</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Turnover__c.field-meta.xml
<CustomField>
    <fullName>Turnover__c</fullName>
    <label>Turnover</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Type_of_Display__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Display__c</fullName>
    <label>Type of Display</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Display</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Wesmarc_Factory_Visit__c.field-meta.xml
<CustomField>
    <fullName>Wesmarc_Factory_Visit__c</fullName>
    <label>Wesmarc Factory Visit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Wesmarc_Factory_Visit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Wesmarc_Factory_Visit_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Wesmarc_Factory_Visit_Remarks__c</fullName>
    <label>Wesmarc Factory Visit Remarks</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Where_they_got_to_know_about_us__c.field-meta.xml
<CustomField>
    <fullName>Where_they_got_to_know_about_us__c</fullName>
    <label>Where they got to know about us</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Where_they_got_to_know_about_us</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Years_in_Business__c.field-meta.xml
<CustomField>
    <fullName>Years_in_Business__c</fullName>
    <label>Years in Business</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadConversionUtility.cls
public class LeadConversionUtility  {
    /**************************************************************** 
* Class Name  : LeadConversionUtility   @Company  : Fingertip    @Created Date  : 15-4-2025  
@description : lead object to contact ,account, opportunity conversion   @author  :Nachiketha   @User By  : - LeadToOpportunity_Conversion_Cmp
* Change Log: 
* ----------------------------------------------------------------------------- 
* Ver |   Author      |   Date        |   Description 
* ----------------------------------------------------------------------------- 
* 1.0 |   Nanma  |  15-4-2025 |   Initial version      
* -------------------------------------------------------------------
**************************************************************** */    
  
    /*  Method Name: convertLead  * Date: 15/04/2025  @author: Nanma  * @description: custom Lead Conversion
* @parameters: lead list */    
    @auraEnabled
    public static string convertLead(string leadId) {
            String accRecordTypeID, recordId;
            // Retrieve the lead
            Lead lead = [SELECT Id, Phone, Appx_Display_Space_They_Own_Sqft__c, Architect_Name__c, Company_Location__c, 
                         	Display_Size_can_be_given_to_Westeam__c, Email, Existing_Business_experience_in_this_Ind__c,
                         	Exiting_Business__c, Looking_for_Wesmarc_dealership__c, MobilePhone, Showroom_Address__c, Source_Type__c, 
                         	Sub_Source__c, Tentative_Date_of_Lead_Closure__c, Turnover__c, Type_of_Display__c, Website, Wesmarc_Factory_Visit__c, 
                         	Wesmarc_Factory_Visit_Remarks__c, Where_they_got_to_know_about_us__c, Years_in_Business__c, IsConverted,Key_Account__c, 
                         	Enquiry_Type__c,LastName,FirstName,Exisiting_Customer__c,recordType.Name FROM Lead WHERE Id = :leadId LIMIT 1];
        	if (lead.IsConverted) {
                System.debug('Lead is already converted.');
                return null;
            }
        
        if(lead.recordType.Name != 'New Channel Partner') {
            Account acc = new Account();
            
            if(lead.Key_Account__c !=null ){
                acc.Id = lead.Key_Account__c;
            }else{
                string firstname = (lead.FirstName !=NULL?lead.FirstName: '');
                acc.Name = firstname +'' +lead.LastName;
                if(lead.recordType.Name == 'B2B'){
                    accRecordTypeID = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get(lead.Enquiry_Type__c).getRecordTypeId();
                    
                }else if(lead.recordType.Name == 'B2C'){
                    accRecordTypeID = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Customer').getRecordTypeId();   
                }else if(lead.recordType.Name == 'Others'){
                    accRecordTypeID = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Others').getRecordTypeId();  
                }
                acc.RecordTypeId = accRecordTypeID;
            }
            try{
            upsert acc;
            }catch(Exception ex){
                ExceptionHandler.addLog(ex, string.valueof(acc), 'LeadConversionUtility',leadId );
            }
            
            // Set up lead conversion with this Account
            Database.LeadConvert leadConvert = new Database.LeadConvert();
            leadConvert.setLeadId(lead.Id);
            leadConvert.setAccountId(acc.Id);
            leadConvert.setDoNotCreateOpportunity(false);
            leadConvert.setConvertedStatus('Qualified');
            
            Database.LeadConvertResult result = Database.convertLead(leadConvert);
            if (result.isSuccess()) {
              
                Id contactId = result.getContactId();
                Id opportunityId = result.getOpportunityId();
                  recordId = opportunityId;
                System.debug('Conversion successful:');
                System.debug('Account Id: ' +result.getAccountId());
                System.debug('Contact Id: ' + contactId);
                System.debug('Opportunity Id: ' + opportunityId);
                Opportunity opp = new opportunity();
                opp.Id = opportunityId;
                string oppRecordTypeID = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get(lead.recordType.Name).getRecordTypeId();  
                opp.recordTypeId = oppRecordTypeID;
                try{
                    update opp;
                }catch(Exception ex){
                    ExceptionHandler.addLog(ex, string.valueof(opp), 'LeadConversionUtility',leadId );
                }
                
                
            } else {
                System.debug('Lead conversion failed.');
                throw new AuraHandledException('An Error Occured');
            }
            
        }
        
        else if(lead.recordType.Name == 'New Channel Partner') {
            Channel_Partner__c cp = New Channel_Partner__c();
              string firstname = (lead.FirstName !=NULL?lead.FirstName: '');
            cp.Name = firstname + lead.LastName;
            cp.Alternate_Mobile__c = lead.Phone;
            cp.Appx_Display_Space_They_Own_Sqft__c = lead.Appx_Display_Space_They_Own_Sqft__c;
            cp.Architect_Name__c = lead.Architect_Name__c;
            cp.Company_Location__c = lead.Company_Location__c;
            cp.Display_Size_can_be_given_to_Westeam__c = lead.Display_Size_can_be_given_to_Westeam__c;
            cp.Email__c = lead.Email;
            cp.Existing_Business_experience_in_this_Ind__c = lead.Existing_Business_experience_in_this_Ind__c;
            cp.Exiting_Business__c = lead.Exiting_Business__c;
            cp.Looking_for_Wesmarc_dealership__c = lead.Looking_for_Wesmarc_dealership__c;
            cp.Mobile__c = lead.MobilePhone;
            cp.Showroom_Address__c = lead.Showroom_Address__c;
            cp.Source_Type__c = lead.Source_Type__c;
            cp.Status__c = 'Onboarded';
            cp.Sub_Source__c = lead.Sub_Source__c;
            cp.Tentative_Date_of_Lead_Closure__c = lead.Tentative_Date_of_Lead_Closure__c;
            cp.Turnover__c = lead.Turnover__c;
            cp.Type_of_Display__c = lead.Type_of_Display__c;
            cp.Website__c = lead.Website;
            cp.Wesmarc_Factory_Visit__c = lead.Wesmarc_Factory_Visit__c;
            cp.Wesmarc_Factory_Visit_Remarks__c = lead.Wesmarc_Factory_Visit_Remarks__c;
            cp.Where_they_got_to_know_about_us__c = lead.Where_they_got_to_know_about_us__c;
            cp.Years_in_Business__c = lead.Years_in_Business__c;
            try {
                insert cp;
                
                recordId = cp.Id;
            }
            catch(DmlException ex) {
                System.debug('Lead conversion failed.');
                  ExceptionHandler.addLog(ex, string.valueof(cp), 'LeadConversionUtility',leadId );
                throw new AuraHandledException('An Error Occured');
            }
            Database.LeadConvert leadConvert = new Database.LeadConvert();
            leadConvert.setLeadId(lead.Id);
            leadConvert.setDoNotCreateOpportunity(true);
            leadConvert.setConvertedStatus('Qualified');
            
            Database.LeadConvertResult result = Database.convertLead(leadConvert);
            Account ac = new Account();
            ac.Id = result.getAccountId();
            
            delete ac;
            
        }
        return recordId;
    }
    
    
    
}