force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarded</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/Sales_Funnel__c.object-meta.xml
<CustomObject>
    <label>Monthly Sales Pipeline</label>
    <nameField>
        <displayFormat>SF -{0000}</displayFormat>
        <label>Monthly Sales Pipeline Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Sales Pipeline</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Funnel__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipName>Sales_Funnel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Number_of_Doors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Doors__c</fullName>
    <label>Number of Doors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Order_Time_line_Time_Frame_Month__c.field-meta.xml
<CustomField>
    <fullName>Order_Time_line_Time_Frame_Month__c</fullName>
    <label>Order Time line/ Time Frame Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Order_Time_line_Time_Frame_Year__c.field-meta.xml
<CustomField>
    <fullName>Order_Time_line_Time_Frame_Year__c</fullName>
    <label>Order Time line/ Time Frame	Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Sales_Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OCG Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Funnel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Postpone</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Calculate_Executive_Summary_Test.cls
@isTest
public class Calculate_Executive_Summary_Test {
@isTest
     public static void method1(){
         User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Sales Team'].Id,
            LastName = 'last',
            Email = 'testbrm@brm.com',
            Username = 'testbrm@brm.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'     
        );
        insert u;  
            Channel_Partner__c cp = new Channel_Partner__c(Name = 'CP Test');
        insert cp;
        
        Id recordType = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('B2B').getRecordTypeId();
        
        Lead l = new Lead(Salutation = 'Mr.', FirstName = 'Lead', LastName = 'Test', Executive_Name__c = u.Id, Manager__c = u.Id,
                         	Exisiting_Customer__c = 'No', Channel_Partner__c = cp.Id, Enquiry_Type__c = 'Builders', RecordTypeId = recordType);
        insert l;
         Sales_Funnel__c sf = NEW Sales_Funnel__c();
         sf.Status__c='Open';
         sf.Number_of_Doors__c=2;
         sf.Sales_Person_Name__c=u.id;
         sf.Order_Time_line_Time_Frame_Month__c ='JULY';
          sf.Order_Time_line_Time_Frame_Year__c ='2025';
         insert sf;
          Test.startTest();
        database.executeBatch(new Calculate_Executive_Summary(date.newInstance(2025,7,01)));


        Test.stopTest();
    }
}