force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <label>Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarded</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Sub_Source__c</fullName>
    <label>Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Source_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/Sales_Funnel__c.object-meta.xml
<CustomObject>
    <label>Monthly Sales Pipeline</label>
    <nameField>
        <displayFormat>SF -{0000}</displayFormat>
        <label>Monthly Sales Pipeline Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Sales Pipeline</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Funnel__c/fields/Actual_Closed__c.field-meta.xml
<CustomField>
    <fullName>Actual_Closed__c</fullName>
    <label>Actual / Closed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Business_Clients__c.field-meta.xml
<CustomField>
    <fullName>Business_Clients__c</fullName>
    <label>Business Clients</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Designer</fullName>
            </value>
            <value>
                <fullName>Retails Customer</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipName>Sales_Funnel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Door_Application__c.field-meta.xml
<CustomField>
    <fullName>Door_Application__c</fullName>
    <label>Door Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Door_Application</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Door_Category__c.field-meta.xml
<CustomField>
    <fullName>Door_Category__c</fullName>
    <label>Door Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Door_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Key_Account__c.field-meta.xml
<CustomField>
    <fullName>Key_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Key Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Funnel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Monthly Sales Pipeline</relationshipLabel>
    <relationshipName>Monthly_Sales_Pipeline</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
            <value>
                <fullName>Wes Team</fullName>
            </value>
            <value>
                <fullName>Own</fullName>
            </value>
            <value>
                <fullName>Repeat</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Number_of_Doors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Doors__c</fullName>
    <label>Number of Doors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Monthly Sales Pipeline</relationshipLabel>
    <relationshipName>Monthly_Sales_Pipeline</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Order_Staus__c.field-meta.xml
<CustomField>
    <fullName>Order_Staus__c</fullName>
    <label>Order Staus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yet to submit the quote</fullName>
            </value>
            <value>
                <fullName>quote submitted</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Lead won</fullName>
            </value>
            <value>
                <fullName>Lead lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Order_Time_line_Time_Frame_Month__c.field-meta.xml
<CustomField>
    <fullName>Order_Time_line_Time_Frame_Month__c</fullName>
    <label>Order Time line/ Time Frame Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Order_Time_line_Time_Frame_Year__c.field-meta.xml
<CustomField>
    <fullName>Order_Time_line_Time_Frame_Year__c</fullName>
    <label>Order Time line/ Time Frame	Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Postpone_Door_Quality__c.field-meta.xml
<CustomField>
    <fullName>Postpone_Door_Quality__c</fullName>
    <label>Postpone Door Quality</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Previous_Month_Backlog__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_Backlog__c</fullName>
    <label>Previous Month Backlog</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Project_Category__c.field-meta.xml
<CustomField>
    <fullName>Project_Category__c</fullName>
    <label>Project Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Reason_for_Loosing_the_Order__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Loosing_the_Order__c</fullName>
    <label>Reason for Loosing the Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Budget Issue</fullName>
            </value>
            <value>
                <fullName>CPL Veneer</fullName>
            </value>
            <value>
                <fullName>Custom / Features</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Sales_Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OCG Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Funnel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Funnel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Postpone</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Source_Mapping__mdt/Source_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Source Mapping</label>
    <pluralLabel>Source Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Source_Mapping__mdt/fields/Lead_source__c.field-meta.xml
<CustomField>
    <fullName>Lead_source__c</fullName>
    <label>Lead source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Source_Mapping__mdt/fields/Sales_Pipeline_source__c.field-meta.xml
<CustomField>
    <fullName>Sales_Pipeline_source__c</fullName>
    <label>Sales Pipeline source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MassInsertController.cls
public class MassInsertController {

    @AuraEnabled
    public static void insertCustomRecords(List<Map<String, Object>> recordsToInsert) {
        List<Sales_Funnel__c> funnels = new List<Sales_Funnel__c>();

        for (Map<String, Object> row : recordsToInsert) {
            Sales_Funnel__c funnel = new Sales_Funnel__c();
            system.debug(row);
            if (row != null) {
                system.debug(row.keyset());
                system.debug(row.values());
                if (row.containsKey('Lead__c')) funnel.Lead__c = (Id)row.get('Lead__c');
                if (row.containsKey('Key_Account__c')) funnel.Key_Account__c = (Id)row.get('Key_Account__c');
                if (row.containsKey('Opportunity__c')) funnel.Opportunity__c = (Id)row.get('Opportunity__c');
                if (row.containsKey('Channel_Partner__c')) funnel.Channel_Partner__c = (Id)row.get('Channel_Partner__c');
                if (row.containsKey('Sales_Person_Name__c')) funnel.Sales_Person_Name__c = (Id)row.get('Sales_Person_Name__c');
                if (row.containsKey('Business_Clients__c')) funnel.Business_Clients__c = (String)row.get('Business_Clients__c');
                if (row.containsKey('Project_Category__c')) funnel.Project_Category__c = (String)row.get('Project_Category__c');
                if (row.containsKey('Project_Name__c')) funnel.Project_Name__c = (String)row.get('Project_Name__c');
                if (row.containsKey('Project_Site_Stage__c')) funnel.Project_Site_Stage__c = (String)row.get('Project_Site_Stage__c');
                if (row.containsKey('State__c')) funnel.State__c = (String)row.get('State__c');
                if (row.containsKey('Status__c')) funnel.Status__c = (String)row.get('Status__c');
                if (row.containsKey('Customer_Name__c')) funnel.Customer_Name__c = (String)row.get('Customer_Name__c');
                if (row.containsKey('Region__c')) funnel.Region__c = (String)row.get('Region__c');
                if (row.containsKey('Order_Staus__c')) funnel.Order_Staus__c = (String)row.get('Order_Staus__c');
                if (row.containsKey('Order_Time_line_Time_Frame_Year__c')) funnel.Order_Time_line_Time_Frame_Year__c = (String)row.get('Order_Time_line_Time_Frame_Year__c');
                if (row.containsKey('Order_Time_line_Time_Frame_Month__c')) funnel.Order_Time_line_Time_Frame_Month__c = (String)row.get('Order_Time_line_Time_Frame_Month__c');
                if (row.containsKey('Reason_for_Loosing_the_Order__c')) funnel.Reason_for_Loosing_the_Order__c = (String)row.get('Reason_for_Loosing_the_Order__c');
                if (row.containsKey('Door_Application__c')) funnel.Door_Application__c = (String)row.get('Door_Application__c');
                if (row.containsKey('Door_Category__c')) funnel.Door_Category__c = (String)row.get('Door_Category__c');
                if (row.containsKey('Postpone_Door_Quality__c')) funnel.Postpone_Door_Quality__c = row.get('Postpone_Door_Quality__c') != null ? Integer.valueOf(row.get('Postpone_Door_Quality__c').toString()) : null;
                if (row.containsKey('Number_of_Doors__c')) funnel.Number_of_Doors__c = row.get('Number_of_Doors__c') != null ? Integer.valueOf(row.get('Number_of_Doors__c').toString()) : null;
                if (row.containsKey('Lead_Source__c')) funnel.Lead_Source__c = (String)row.get('Lead_Source__c');
                if (row.containsKey('Previous_Month_Backlog__c')) funnel.Previous_Month_Backlog__c = row.get('Previous_Month_Backlog__c') != null ? Integer.valueOf(row.get('Previous_Month_Backlog__c').toString()) : null;
                if (row.containsKey('Actual_Closed__c')) funnel.Actual_Closed__c = row.get('Actual_Closed__c') != null ? Integer.valueOf(row.get('Actual_Closed__c').toString()) : null;
                
                funnels.add(funnel);
                system.debug(funnel);
            } else {
                throw new AuraHandledException('Row is not having any values');
            }
            
        }

        if (!funnels.isEmpty()) {
            insert funnels;
        }
    }
    
    @AuraEnabled
    public static Map<String, String> LeadDefaults(String leadId) {
        Map<String, String> leadValues = new Map<String, String>();
        system.debug('Lead Record Id: '+ leadId);
        
        Lead ld = [SELECT Id, Name, Source_Type__c, Timeline_Year__c, Timeline_Month__c, Primary_Contact_Person__c, Enquiry_Type__c, State__c, 
                   Region__c, Door_Application__c, Door_Category__c, Number_of_Doors_Client_Looking_for__c, Project_Category__c, 
                   Project_Site_Stage__c, Project_Name__c, Key_Account__c, Sub_Source__c, Channel_Partner__c 
                   FROM Lead WHERE Id =: leadId];
        System.debug('Lead Record: '+ld);
        
        Map<String, String> SrcMap = new Map<String, String>();
            for (Source_Mapping__mdt src : [SELECT Lead_source__c, Sales_Pipeline_source__c FROM Source_Mapping__mdt]) {
                SrcMap.put(src.Lead_source__c, src.Sales_Pipeline_source__c);
            }
        
        if(ld.Id != null) {
            if(ld.Project_Name__c !=null && ld.Project_Name__c !=''){
                leadValues.put('Project_Name__c', ld.Project_Name__c);
            }else{
                leadValues.put('Project_Name__c', ld.Name);
            }        
            leadValues.put('Customer_Name__c', ld.Name);
            leadValues.put('State__c', ld.State__c);
            leadValues.put('Region__c', ld.Region__c);
            leadValues.put('Key_Account__c', ld.Key_Account__c);
            leadValues.put('Sales_Person_Name__c', UserInfo.getUserId());
            leadValues.put('Project_Category__c', ld.Project_Category__c);
            leadValues.put('Business_Clients__c', ld.Enquiry_Type__c);
            leadValues.put('Channel_Partner__c', ld.Channel_Partner__c);
            leadValues.put('Door_Application__c', ld.Door_Application__c);
            if(ld.Source_Type__c!=null && SrcMap.containskey(ld.Source_Type__c)){
                leadValues.put('Lead_Source__c', SrcMap.get(ld.Source_Type__c));
            }
            leadValues.put('Door_Category__c', ld.Door_Category__c);
            leadValues.put('Project_Site_Stage__c', ld.Project_Site_Stage__c);
            leadValues.put('Order_Time_line_Time_Frame_Year__c', ld.Timeline_Year__c);
            leadValues.put('Order_Time_line_Time_Frame_Month__c', ld.Timeline_Month__c);
            leadValues.put('Number_of_Doors__c', String.valueOf(ld.Number_of_Doors_Client_Looking_for__c));
        }
        
        system.debug(leadValues);
        return leadValues;
    }
}